export default [
  {
    "id": 1,
    "title": "Captain America: The First Avenger",
    "year": 2011,
    "rating": 6.9,
    "details": "Steve Rogers, a rejected military soldier transforms into Captain America after taking a dose of a Super-Soldier serum. But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization.",
    "director": "Joe Johnston",
    "starring": "Chris Evans, Hugo Weaving, Samuel L. Jackson, Hayley Atwell",
    "gross": "$176.65M",
    "image": "https://m.media-amazon.com/images/M/MV5BMTYzOTc2NzU3N15BMl5BanBnXkFtZTcwNjY3MDE3NQ@@._V1_UX140_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 2,
    "title": "Iron Man",
    "year": 2008,
    "rating": 7.9,
    "details": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    "director": "Jon Favreau",
    "starring": "Robert Downey Jr. Gwyneth Paltrow, Terrence Howard, Jeff Bridges",
    "gross": "$318.41M",
    "image": "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 3,
    "title": "The Incredible Hulk",
    "year": 2008,
    "rating": 6.8,
    "details": "Bruce Banner, a scientist on the run from the U.S. Government, must find a cure for the monster he turns into, whenever he loses his temper.",
    "director": "Louis Leterrier",
    "starring": "Edward Norton, Liv Tyler, Tim Roth, William Hurt",
    "gross": "$134.52M",
    "image": "https://m.media-amazon.com/images/M/MV5BMTUyNzk3MjA1OF5BMl5BanBnXkFtZTcwMTE1Njg2MQ@@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 4,
    "title": "Iron Man 2",
    "year": 2010,
    "rating": 7.0,
    "details": "With the world now aware of his identity as Iron Man, Tony Stark must contend with both his declining health and a vengeful mad man with ties to his father's legacy.",
    "director": "Jon Favreau",
    "starring": "Robert Downey Jr., Mickey Rourke, Gwyneth Paltrow, Don Cheadle",
    "gross": "$312.43M",
    "image": "https://m.media-amazon.com/images/M/MV5BMTM0MDgwNjMyMl5BMl5BanBnXkFtZTcwNTg3NzAzMw@@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 5,
    "title": "Thor",
    "year": 2011,
    "rating": 7.0,
    "details": "The powerful, but arrogant god Thor, is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.",
    "director": "Kenneth Branagh",
    "starring": "Chris Hemsworth, Anthony Hopkins, Natalie Portman, Tom Hidleston",
    "gross": "$181.03M",
    "image": "https://m.media-amazon.com/images/M/MV5BOGE4NzU1YTAtNzA3Mi00ZTA2LTg2YmYtMDJmMThiMjlkYjg2XkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 6,
    "title": "The Avengers",
    "year": 2012,
    "rating": 8.1,
    "details": "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    "director": "Joss Whedon",
    "starring": "Robert Downey Jr., Chris Evans, Scarlett Johansson, Jeremy Renner",
    "gross": "$623.36M",
    "image": "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 7,
    "title": "Iron Man 3",
    "year": 2013,
    "rating": 7.2,
    "details": "When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.",
    "director": "Shane Black",
    "starring": "Robert Downey Jr., Guy Pearce, Gwyneth Paltrow, Don Cheadle",
    "gross": "$409.01M",
    "image": "https://m.media-amazon.com/images/M/MV5BMjE5MzcyNjk1M15BMl5BanBnXkFtZTcwMjQ4MjcxOQ@@._V1_UY209_CR3,0,140,209_AL_.jpg"
  },
  {
    "id": 8,
    "title": "Thor: The Dark World",
    "year": 2013,
    "rating": 7,
    "details": "When Dr. Jane Foster gets cursed with a powerful entity known as the Aether, Thor is heralded of the cosmic event known as the Convergence and the genocidal Dark Elves.",
    "director": "Alan Taylor",
    "starring": "Chris Hemsworth, Natalie Portman, Tom Hidleston, Stellan Skarsgard",
    "gross": "$206.36M",
    "image": "https://m.media-amazon.com/images/M/MV5BMTQyNzAwOTUxOF5BMl5BanBnXkFtZTcwMTE0OTc5OQ@@._V1_UY209_CR3,0,140,209_AL_.jpg"
  },
  {
    "id": 9,
    "title": "Captain America: The Winter Soldier",
    "year": 2014,
    "rating": 7.8,
    "details": "As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier.",
    "director": "Anthony Russo, Joe Russo",
    "starring": "Chris Evans, Samuel L. Jackson, Scarlett Johansson, Robert Redford",
    "gross": "$259.77M",
    "image": "https://m.media-amazon.com/images/M/MV5BMzA2NDkwODAwM15BMl5BanBnXkFtZTgwODk5MTgzMTE@._V1_UY209_CR1,0,140,209_AL_.jpg"
  },
  {
    "id": 10,
    "title": "Guardians of the Galaxy",
    "year": 2014,
    "rating": 8.1,
    "details": "A group of intergalactic criminals are forced to work together to stop a fanatical warrior from taking control of the universe.",
    "director": "James Gunn",
    "starring": "Chris Pratt, Vin Diesel, Bradley Cooper, Zoe Saldana",
    "gross": "$333.18M",
    "image": "https://m.media-amazon.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 11,
    "title": "Guardians of the Galaxy Vol. 2",
    "year": 2017,
    "rating": 7.7,
    "details": "The Guardians must fight to keep their newfound family together as they unravel the mystery of Peter Quill's true parentage.",
    "director": "James Gunn",
    "starring": "Chris Pratt, Vin Diesel, Dave Bautista, Zoe Saldana",
    "gross": "$389.81M",
    "image": "https://m.media-amazon.com/images/M/MV5BMTg2MzI1MTg3OF5BMl5BanBnXkFtZTgwNTU3NDA2MTI@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 12,
    "title": "Avengers: Age of Ultron",
    "year": 2015,
    "rating": 7.4,
    "details": "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.",
    "director": "Joss Whedon",
    "starring": "Robert Downey Jr. Chris Evans, Mark Ruffalo, Chris Hemsworth",
    "gross": "$459.01M",
    "image": "https://m.media-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 13,
    "title": "Ant-Man",
    "year": 2015,
    "rating": 7.3,
    "details": "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.",
    "director": "Peyton Reed",
    "starring": "Paul Rudd, Michael Douglas, Corey Stoll, Evangeline Lilly",
    "gross": "$180.20M",
    "image": "https://m.media-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 14,
    "title": "Captain America: Civil War",
    "year": 2016,
    "rating": 7.8,
    "details": "Political involvement in the Avengers' activities causes a rift between Captain America and Iron Man.",
    "director": "Anthony Russo, Joe Russo",
    "starring": "Chris Evans, Robert Downey Jr., Scarlett Johansson, Sebastian Stan",
    "gross": "$408.08M",
    "image": "https://m.media-amazon.com/images/M/MV5BMjQ0MTgyNjAxMV5BMl5BanBnXkFtZTgwNjUzMDkyODE@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 15,
    "title": "Spider-Man: Homecoming",
    "year": 2017,
    "rating": 7.5,
    "details": "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and finds himself on the trail of a new menace prowling the skies of New York City.",
    "director": "Jon Watts",
    "starring": "Tom Holland, Michael Keaton, Robert Downey Jr., Marisa Tomei",
    "gross": "$334.20M",
    "image": "https://m.media-amazon.com/images/M/MV5BNTk4ODQ1MzgzNl5BMl5BanBnXkFtZTgwMTMyMzM4MTI@._V1_UX140_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 16,
    "title": "Doctor Strange",
    "year": 2016,
    "rating": 7.5,
    "details": "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
    "director": "Scott Derrickson",
    "starring": "Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams, Benedict Wong",
    "gross": "$232.64M",
    "image": "https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 17,
    "title": "Thor - Ragnarok",
    "year": 2017,
    "rating": 7.9,
    "details": "Thor is imprisoned on the planet Sakaar, and must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.",
    "director": "Taika Waititi",
    "starring": "Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Mark Ruffalo",
    "gross": "$315.06M",
    "image": "https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 18,
    "title": "Black Panther",
    "year": 2018,
    "rating": 7.4,
    "details": "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
    "director": "Ryan Coogler",
    "starring": "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Danai Gurira",
    "gross": "$700.06M",
    "image": "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 19,
    "title": "Avengers: Infinity War",
    "year": 2018,
    "rating": 8.6,
    "details": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    "director": "Anthony Russo, Joe Russo",
    "starring": "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans",
    "gross": "$678.82M",
    "image": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 20,
    "title": "Ant-Man and the Wasp",
    "year": 2018,
    "rating": 7.2,
    "details": "As Scott Lang balances being both a Super Hero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.",
    "director": "Peyton Reed",
    "starring": "Paul Rudd, Evangeline Lilly, Michael Pena, Walton Goggins",
    "gross": "$216.64M",
    "image": "https://m.media-amazon.com/images/M/MV5BYjcyYTk0N2YtMzc4ZC00Y2E0LWFkNDgtNjE1MzZmMGE1YjY1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UY209_CR0,0,140,209_AL_.jpg"
  },
  {
    "id": 21,
    "title": "Captain Marvel",
    "year": 2019,
    "rating": "NA",
    "details": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
    "director": "Anna Boden, Ryan Fleck",
    "starring": "Mckenna Grace, Brie Larson, Gemma Chan, Jude Law",
    "gross": "NA",
    "image": "https://m.media-amazon.com/images/M/MV5BMTYzNDc5NzY5OF5BMl5BanBnXkFtZTgwMjA0OTUzNjM@._V1_UY209_CR0,0,140,209_AL_.jpg"
  }
]